apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-website
  namespace: demo
spec:
  to:
    kind: Service
    name: my-website
  port:
    targetPort: 8080
  tls:
    termination: edge

